disabled_rules:
  - line_length
  - identifier_name
  - nesting
  - type_name
  - explicit_enum_raw_value
  - file_length
  - function_body_length
  - function_parameter_count  # Allow 6+ parameters for DateTime and Area factory methods
  - type_body_length  # Comprehensive test suites can be longer than 250 lines
  - trailing_comma  # Conflicts with swift-format which prefers trailing commas
  - redundant_discardable_let  # Preserve 'let _ =' in result builder contexts (required for Swift 6.0+)

opt_in_rules:
  - empty_count
  - explicit_init
  - sorted_imports
  - force_cast
  - force_try
  - closure_spacing
  - operator_usage_whitespace
  - private_outlet
  - redundant_nil_coalescing
  - empty_string
  - literal_expression_end_indentation
  - single_test_class
  - sorted_first_last
  - vertical_whitespace
  - strict_fileprivate
  - legacy_random
  - no_extension_access_modifier
  - colon
  
included:
  - Package.swift
  - Sources
  - Tests

excluded:
  - Carthage
  - Pods
  - fastlane
  - build

analyzer_rules:
  - unused_import

colon:
  apply_to_dictionaries: true

vertical_whitespace:
  max_empty_lines: 1
